### PR TITLE
Add humanitarian plan codelist

### LINKED ISSUE #163: Add "Humanitarian Plan" codelist
* On vocab codelist: https://codelists.codeforiati.org/HumanitarianScopeVocabulary/#2-1
 * Source URL: https://fts.unocha.org/plan-code-list-iati
 * Download URL: https://fts.unocha.org/download/126339/download
 * 27 publishers are using it currently: https://analytics.codeforiati.org/codelist/2/humanitarian-scope_@vocabulary.html

### PR DESCRIPTION
**Pull request by andylolz**
Fixes https://github.com/codeforIATI/Unofficial-Codelists/issues/163.

### CODE REVIEW

**Comment by markbrough** [comment]
This looks very nice!! But would it make sense to also include a couple of the other columns, at least plan type and plan year?

**Comment by andylolz** [comment]
Right yes, v good point…

**Comment by andylolz** [comment]
Okay, I’ve added everything! (I also renamed the columns in the source, and fixed the dates so they’re ISO-8601.)

WDYT, @markbrough?

**Comment by andylolz** [comment]
Gonna merge because I guess this is fine now.

**Pull request merged**
