### PR TITLE
Add reporting org codelist

### PR DESCRIPTION
**Pull request by andylolz**
WIP because it would be nice to make reporting org type use codes rather than narratives.

### CODE REVIEW

**Comment by andylolz** [comment]
Blocked because it would be nice to make reporting org type use codes rather than narratives.

**Comment by markbrough** [comment]
I used this mapping file for reporting organisations:
https://github.com/IATI/ckanext-iati/blob/d1a8776181c494eed0fd33c85f44878c88349613/ckanext/iati/lists.py#L27-L38

We could also consider mapping countries by pulling in this list, though perhaps as a separate file?
https://github.com/IATI/ckanext-iati/blob/d1a8776181c494eed0fd33c85f44878c88349613/ckanext/iati/countries.py

**Comment by markbrough** [comment]
(But I think this is also good to go as it is!)

**Comment by markbrough** [comment]
Sample output:
```xml
<codelist xmlns:codeforiati="https://codeforiati.org/" name="ReportingOrganisation" xml:lang="en" complete="1" embedded="0">
    <metadata>
        <name>
            <narrative>Reporting Organisation</narrative>
            <narrative xml:lang="fr">Organisation déclarante</narrative>
        </name>
        <url>https://iatiregistry.org/publisher</url>
        <category>
            <narrative>Replicated</narrative>
        </category>
    </metadata>
    <codelist-items>
        <codelist-item status="active">
            <code>AU-5</code>
            <name>
                <narrative>Australia - Department of  Foreign Affairs and Trade</narrative>
            </name>
            <codeforiati:organisation-type-code>10</codeforiati:organisation-type-code>
            <codeforiati:organisation-type>Government</codeforiati:organisation-type>
            <codeforiati:hq-country-or-region>Australia</codeforiati:hq-country-or-region>
        </codelist-item>
    </codelist-items>
</codelist>

**Comment by andylolz** [comment]
Nice one, this is great! Thanks!

**Pull request merged**
