### PR TITLE
Use source for humanitarian global clusters

### PR DESCRIPTION
**Pull request by andylolz**
Currently we’re using our own spreadsheet for this codelist, but I think we can just use the source one.

### CODE REVIEW

**Comment by matmaxgeds** [comment]
Thanks......saves me manually tracking the changes to their sheet!

**Comment by andylolz** [comment]
> saves me manually tracking the changes to their sheet!

Exactly, yes. In fact, I think we should probably delete the replicated sheet (though not the workbook in general, as I think the other sheets are still required) and just rely on the source. What do you think, @matmaxgeds?

**Comment by andylolz** [comment]
Merged. Do you mind if I delete this sheet, @matmaxgeds?
https://docs.google.com/spreadsheets/d/1o1SQDqfFTBgUJO2k83mfFlLtgpwUUkEbc3gjRgIWJSo/edit#gid=1574305742

**Comment by matmaxgeds** [comment]
Please do :)

**Pull request merged**
